[AOS 705] new motion validator for approaches
Omnirobotic/ompl pull request #1
Opened 2020-12-02 21:04 UTC by radu-omni

2020-12-03 12:55 UTC, SepehrGharaaty requested changes

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/base/src/DiscreteMotionValidator.cpp
> +    OMPL_DEBUG("PROBLEM!!! CALLING check motion in OMPL!");
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/base/src/DiscreteMotionValidator.cpp
> +    OMPL_DEBUG("PROBLEM!!! CALLING check motion in OMPL!");
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(msg.c_str());
comment out these

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +        std::cout << "smoothBSpline: starting step : " + std::to_string(s) << std::endl;
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +        std::cout << "smoothBSpline: n1 is : " + std::to_string(n1) << std::endl;
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +                        std::cout << "smoothBSpline: distance " + std::to_string(si->distance(states[i], temp1)) + " is greater than min change: " + std::to_string(minChange) << std::endl;
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +                    }
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            std::cout << "smoothBSpline: BREAK is called at step : " + std::to_string(s) << std::endl;
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(end_msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(end_msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(msg.c_str());
remove/comment out

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(end_msg.c_str());
comment out

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(msg.c_str());
comment out

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +    OMPL_DEBUG(end_msg.c_str());
comment out

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +                OMPL_DEBUG(msg.c_str());
comment out

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +                OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +                OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            OMPL_DEBUG(msg.c_str());
remove

2020-12-03 12:55 UTC, SepehrGharaaty commented on src/ompl/geometric/src/PathSimplifier.cpp
> +            OMPL_DEBUG(msg.c_str());
remove

2020-12-09 13:21 UTC, PierreLucGriffin commented
More tests need to be done. On hold until then.

2020-12-09 13:21 UTC, closed without merging